apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: admin-tp5
  labels:
    test: netpol
spec:
  replicas: 1
  selector:
    matchLabels:
      test: netpol
  template:
    metadata:
      labels:
        test: netpol
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "testuser"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "testdb"
          ports:
            - containerPort: 5432
              name: db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: admin-tp5
  labels:
    test: netpol
spec:
    selector:
        test: netpol
    ports:
        - port: 5432
          protocol: TCP
          targetPort: db