apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  namespace: admin-tp2
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pvc-storage
      ports:
        - containerPort: 80
          name: "http"
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: pvc-example