apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example
  namespace: admin-tp2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: pv-example