all:
  hosts:
    master1:
      ansible_host: 34.163.158.116
      ip: 10.20.0.101
      access_ip: 10.20.0.101
    master2:
      ansible_host: 34.155.58.252
      ip: 10.20.0.102
      access_ip: 10.20.0.102
    worker:
      ansible_host: 34.155.232.227
      ip: 10.20.0.103
      access_ip: 10.20.0.103
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
    kube_node:
      hosts:
        worker:
    etcd:
      hosts:
        master1:
    k8s_cluster:
      children:
        kube_node:
    calico_rr:
      hosts: {}
